version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 727646477053.dkr.ecr.ca-central-1.amazonaws.com
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Build started on `date`
      - docker build -t joshi-assign3-ecr .
      - docker tag joshi-assign3-ecr:latest 727646477053.dkr.ecr.ca-central-1.amazonaws.com/joshi-assign3-ecr:$IMAGE_TAG
  post_build:
    commands:
      - docker push 727646477053.dkr.ecr.ca-central-1.amazonaws.com/joshi-assign3-ecr:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"joshi-container","imageUri":"727646477053.dkr.ecr.ca-central-1.amazonaws.com/joshi-assign3-ecr:%s"}]' $IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
